---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chain-no-auth-restrict-networks
spec:
  chain:
    middlewares:
      - name: network-chain-no-auth-restrict-networks@kubernetescrd
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chain-no-auth
spec:
  chain:
    middlewares:
      - name: network-chain-no-auth@kubernetescrd
