apiVersion: v1
kind: ConfigMap
metadata:
  name: qbit-manage-configmap
data:
  config.yml: |
    qbt:
      host: qbittorrent.media.svc.cluster.local:8080
      user: !ENV QBT_USER
      pass: !ENV QBT_PASS

    directory:
      root_dir: /downloads/complete

    cat:
      manual: /downloads/complete/manual/*
      series: /downloads/complete/series/*
      movies: /downloads/complete/movies/*
      ratio: /downloads/complete/ratio/*

    tracker:
      stackoverflow.tech:
        tag: iptorrents
      empirehost.me:
        tag: iptorrents
      bgp.technology:
        tag: iptorrents
