---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-only-local
spec:
  ipAllowList:
    sourceRange:
      - 172.22.0.0/16
      - 172.24.0.0/16
      - 192.168.1.0/24
      - 10.1.60.0/24
      - 10.1.200.0/24
      - 10.8.0.0/24
      - 10.50.40.0/24
      - 10.50.45.0/24
      - 10.96.0.0/16
      - 10.69.0.0/16
