---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./autobrr/ks.yaml
  - ./downloads-pv.yaml
  - ./media-pv.yaml
  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./notifiarr/ks.yaml
  # - ./plex/ks.yaml    # many issues with libraries due to talos (/usr/lib/x86_64-linux-gnu/libresolv.so.2 and
  #                       nvidia ones like /usr/local/glibc/usr/lib/libnvidia-encode.so*)
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./gluetun-service.yaml
  - ./plik/ks.yaml
