---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-webhook-token
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: flux-system/gh-webhook
