---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: observability/grafana
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-wh
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: observability/discord-wh
