apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 80.4.1
      type: oci
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    cleanPrometheusOperatorObjectNames: true
    alertmanager:
      enabled: true
      alertmanagerSpec:
        externalUrl: https://alertmanager.${SECRET_DOMAIN}
        # alertmanagerConfiguration:
        #   name: alertmanager
        #   global:
        #     resolveTimeout: 5m
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-csi
              resources:
                requests:
                  storage: 1Gi
    kubeEtcd:
      service:
        selector:
          component: kube-apiserver # etcd runs on control plane nodes
    kubeProxy:
      enabled: false
    prometheus:
      prometheusSpec:
        externalUrl: https://prometheus.${SECRET_DOMAIN}
        version: v2.55.1 # override 'unsupported Prometheus version' error
        securityContext:
          runAsNonRoot: true
          runAsUser: 64535
          runAsGroup: 64535
          fsGroup: 64535
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        retention: 14d
        retentionSize: 50GB
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 4Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-csi
              resources:
                requests:
                  storage: 50Gi
    prometheus-node-exporter:
      fullnameOverride: node-exporter
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
    grafana:
      enabled: true
      adminUser: ${GRAFANA_USER}
      adminPassword: "${GRAFANA_PASS}"
      persistence:
        enabled: true
        storageClassName: nfs-csi
        size: 5Gi
      sidecar:
        dashboards:
          enabled: true
          searchNamespace: ALL
        datasources:
          enabled: true
      grafana.ini:
        server:
          root_url: https://grafana.${SECRET_DOMAIN}
