apiVersion: v1
kind: ConfigMap
metadata:
  name: arr-filter
data:
  arr-filter.sh: |
    #!/bin/sh
    # Combined Radarr/Sonarr filter script
    # Usage: /scripts/arr-filter-script.sh <ENDPOINT_URL>

    ENDPOINT="$1"
    if [ -z "$ENDPOINT" ]; then
      echo "Error: Provide ENDPOINT as argument (e.g., Radarr or Sonarr URL)" >&2
      exit 1
    fi

    # Build JSON payload (confirmed env vars)
    PAYLOAD=$(cat <<EOF
    {
      "title": "${TORRENT_NAME}",
      "releaseTitle": "${TORRENT_NAME}",
      "size": ${SIZE:-0},
      "indexer": "${INDEXER_NAME}",
      "indexerId": 0,
      "downloadUrl": "${DOWNLOAD_URL}",
      "link": "${INFO_URL}",
      "protocol": "${PROTOCOL:-torrent}",
      "languages": [
        {
          "id": 1,
          "name": "English"
        }
      ],
      "customFormats": [],
      "customFormatScores": [],
      "releaseHash": "",
      "commentUrl": "",
      "publishDate": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    }
    EOF
    )

    # Send to Radarr/Sonarr
    RESPONSE=$(curl -s -X POST "$ENDPOINT" \
      -H "Content-Type: application/json" \
      -d "$PAYLOAD")

    # Check rejection (handles upgrades/rejects)
    if echo "$RESPONSE" | jq -e '.[0].rejected == false' > /dev/null 2>&1; then
      echo "Approved: ${TORRENT_NAME}" >&2
      exit 0
    else
      echo "Rejected: ${TORRENT_NAME}" >&2
      # Log rejections safely (no error on empty/null)
      echo "$RESPONSE" | jq -r '.[0].rejections // empty | .[]' >&2 2>/dev/null || echo "No rejection details" >&2
      exit 1
    fi
