---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      sabnzbd:
        annotations:
          secret.reloader.stakater.com/reload: sabnzbd-secret

        containers:
          pia-tun:
            image:
              repository: olsonalexw/k8s-wireguard-pia
              tag: develop@sha256:4c26dbbab4aaae63ce54990d26c0d7ee17824710d0a0982d772d8db012d7a457
              pullPolicy: Always
            env:
              TZ: ${TIMEZONE}
              LOCAL_NETWORK: "10.69.0.0/16,10.96.0.0/16"
              LOCAL_PORTS: 8080
              PROXY_ENABLED: "true"
            envFrom:
              - secretRef:
                  name: sabnzbd-secret
            resources:
              requests:
                cpu: 11m
                memory: 50M
              limits:
                memory: 50M
            securityContext:
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - NET_ADMIN
                drop:
                  - ALL
          sabnzbd:
            dependsOn: pia-tun
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 4.5.5@sha256:da57e01cdebc547852b6df85c8df8c0e4d87792742c7608c5590dc653b184e8c
            env:
              TZ: ${TIMEZONE}
              PUID: "1001"
              PGID: "1001"
              UMASK: "022"
              SABNZBD__HOST_WHITELIST_ENTRIES: sabnzbd.media.svc.cluster.local, sabnzbd.${SECRET_DOMAIN}
            resources:
              requests:
                cpu: 10m
                memory: 1641M
              limits:
                memory: 3561M
            securityContext:
              runAsUser: 1001
              runAsGroup: 1001
              runAsNonRoot: true
    service:
      sabnzbd:
        controller: *app
        ports:
          http:
            port: 8080
          socks5:
            port: 1080
    ingress:
      sabnzbd:
        enabled: true
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth-restrict-networks@kubernetescrd"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Sabnzbd
          gethomepage.dev/group: Media
          gethomepage.dev/icon: sabnzbd.png
          gethomepage.dev/description: Newsgroup Downloader
          gethomepage.dev/href: https://sabnzbd.${SECRET_DOMAIN}
        hosts:
          - host: "sabnzbd.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: sabnzbd
                  port: http
        tls:
          - hosts:
              - "sabnzbd.${SECRET_DOMAIN}"
            secretName: "${SECRET_DOMAIN/./-}-production-tls"
    persistence:
      config:
        enabled: true
        storageClass: nfs-csi          # Dynamic PVC in /kubernetes/appdata
        accessMode: ReadWriteMany
        size: 2Gi
      media:
        enabled: true
        existingClaim: nfs-media-pvc   # Uses static PVC for /kubernetes/media
      tmp:
        type: emptyDir
    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "Always"
