kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: sabnzbd-secret
    namespace: flux-system
stringData:
    PIA_USER: ENC[AES256_GCM,data:Vj5DoxQ3Maw=,iv:P3i6JGCa5xdWS+oZsbhUxVu4qOlzYnZ5zGt3Co8+W60=,tag:NDF/0P2sf50QbJgB6riQFA==,type:str]
    PIA_PASS: ENC[AES256_GCM,data:ye0it0jvDYRrTsT4q4cAv6o=,iv:nxXe/vU9n8YTR5zOcJ93qD3DX3HarCXTXig7n6QRAT4=,tag:CM0X8kKfeEzReJfYPRPG0Q==,type:str]
    PIA_LOCATIONS: ENC[AES256_GCM,data:kCkJ2n59yatb2A==,iv:tSxDWTSe1/jgOkYuC5pbivHgjtPJVWEnIlWA3wej0U4=,tag:cTmCOnTiip1/uylQ27HkbQ==,type:str]
sops:
    age:
        - recipient: age1h5suln4phcc5qzs2sfmkee39kzhdskmmwzzf5e46egaxqr64l9uskqeh4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVE1CTkdqb0lnWWhzUndp
            b1hqVHM0akJsZGNrdzhZMDhUSEErVE0vVGhzCmFDeWlnR0JDU3FFRzF0TUZtWWNF
            a2tJSEdKblBORnpwUVJxWEpkcEJpdFkKLS0tIFJHWU4rTk5xeWU2Z0xhaWZFY2ZP
            MWZ6TityUDlPZ2Y1OFVOMXhYendGam8KUmSv27cmIOoCh9er3vuuOBr3fRcNRTiP
            m07HhY3E2jQX4NBp+lQbz/yBFEtvOcrnekfk/rk8FWIrLILZvfWXZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T14:42:53Z"
    mac: ENC[AES256_GCM,data:z1etJ+/e7slIlROE5V1c/w0h2WjMTtVR4HhogI8MYSJx/ya6FrXoNY3vfLGO9nRw+k427+IhjhIhPIWiNlxfxQ8xoR+VprurORIPEHf/AxgYtCp4M/vr0TnLAH4kI+Iz1VorJG5gJHcIU/0dP+XA4G1t1YDM5/Y/Z8c/alYs7Gw=,iv:sqjtJQtDfgppHrUSEZTQ+/bi7ESIBa/2KYcvvp+zw7Y=,tag:2nFkWBCCrMEfEaUCBXo28g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
