---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
  namespace: network
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: network/cloudflared
