---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-pia
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: media/qbittorrent/pia
