kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: qbittorrent-secret
    namespace: flux-system
stringData:
    PIA_USER: ENC[AES256_GCM,data:CREXX8Wat8E=,iv:PWP32i7bCjDzxhOo/2KSiCF7nEiyDQthz3ZPL7INMjk=,tag:+NlTzbYdjqmNWwX9MY1HtQ==,type:str]
    PIA_PASS: ENC[AES256_GCM,data:dkPZUxeBm07YjITT+RlccHs=,iv:BGMngwezm3l31lxOrLRSXll6AFlsjYkBXk5jRmkcB4k=,tag:Bkdxy4Yu2DIL01+9fSZzhA==,type:str]
    PIA_LOCATIONS: ENC[AES256_GCM,data:a37OYYg7ptFBSZONERZCUqOX+vndQ1NV5VZP3db4sZUOdkE=,iv:NwP6/FdtaWN6WIv7y5sbtmGFbu2JsGuzQl3bsnOcT1E=,tag:0ZHmivWDthwbLUagnsptHQ==,type:str]
sops:
    age:
        - recipient: age1h5suln4phcc5qzs2sfmkee39kzhdskmmwzzf5e46egaxqr64l9uskqeh4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZFJkU3BJcU5qUGNGNWwy
            QnFOc0ZEYXBuOHQxUE9NUENiZnV5bktSTUhJCjQ2QURMR21lZ2I5SG5XUldYNUZU
            TlNYay83VGV5MzN1UTd1OStEV0pkUXcKLS0tICs5VXJ6cktIc0ROSE5zeDhlSlMr
            ZHJwaGxrNS93K2lCeCtpUXhDV3Y3YlEKxtbJqhEI3NmFDgpUXhNAdV8hKfxDTFCw
            wEqz19lYsGi15H/z8f2ZJvvURL4sZguE1rn8da20Vc/YABuPCocrQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T08:58:19Z"
    mac: ENC[AES256_GCM,data:1mJUCd0nXbcWKglj4F+uOkmr6smVZZT46y0WAwty8XIskQiLFEpxZ6jgKvT0Q47A4eB69UN9+SCcmGDsX3nkzk3ff0Cf0T+kmgtFaZtKgNciLB8j7Tp0epsdb69xS4kjbe50uGWpApNBWn040fNwO6MyL1OC4AZFVOUyP2yIl4U=,iv:obC4Igo6XYvN9h+pBvBH5BrwvAT5JPwEubOXbq3qluA=,tag:iZkOfyrgLCs+Qo7ko2AwFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
