---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-db
  namespace: media
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: sonarr-db-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: postgres-pguser-sonarr
        property: password
    - secretKey: host
      remoteRef:
        key: postgres-pguser-sonarr
        property: host
    - secretKey: port
      remoteRef:
        key: postgres-pguser-sonarr
        property: port
