# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  releaseName: sonarr
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: csi-driver-nfs
      namespace: storage
  values:
    controllers:
      main:
        type: deployment
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/sonarr
              pullPolicy: IfNotPresent
              tag: 4.0.16@sha256:3597fd572f4599c67abbeb8afd3cb85bce8a9e389f0779b7ea1273781544d15c
            env:
              TZ: "America/Detroit"
              SONARR__APPLICATION_URL: "https://sonarr.${SECRET_DOMAIN}"
            resources:
              requests:
                cpu: 15m
                memory: 298M
              limits:
                memory: 1028M
    service:
      main:
        controller: main
        ports:
          http:
            port: 8989
    ingress:
      main:
        enabled: true
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth-restrict-networks@kubernetescrd"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Sonarr
          gethomepage.dev/group: Media
          gethomepage.dev/icon: sonarr.png
          gethomepage.dev/description: TV Show Manager
          gethomepage.dev/href: https://sonarr.${SECRET_DOMAIN}
        hosts:
          - host: "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - "sonarr.${SECRET_DOMAIN}"
            secretName: "${SECRET_DOMAIN/./-}-production-tls"
    persistence:
      config:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteMany
        size: 2Gi
      media:
        enabled: true
        existingClaim: nfs-media-pvc
      downloads:
        enabled: true
        existingClaim: nfs-downloads-pvc

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: "Always"
