apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: sonarr
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: traefik-internal-network
            io.kubernetes.pod.namespace: network
        - matchLabels:
            app.kubernetes.io/name: prowlarr
            io.kubernetes.pod.namespace: media
        - matchLabels:
            app.kubernetes.io/name: notifiarr
            io.kubernetes.pod.namespace: media
        - matchLabels:
            app.kubernetes.io/name: seerr
            io.kubernetes.pod.namespace: media
      toPorts:
        - ports:
            - port: "8989"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prowlarr
            io.kubernetes.pod.namespace: media
      toPorts:
        - ports:
            - port: "9696"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: notifiarr
            io.kubernetes.pod.namespace: media
      toPorts:
        - ports:
            - port: "5454"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: plex
            io.kubernetes.pod.namespace: media
      toPorts:
        - ports:
            - port: "32400"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: qbittorrent
            io.kubernetes.pod.namespace: media
        - matchLabels:
            app.kubernetes.io/name: sabnzbd
            io.kubernetes.pod.namespace: media
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    - toFQDNs:
        - matchName: api.thetvdb.com
        - matchName: api4.thetvdb.com
        - matchName: artworks.thetvdb.com
        - matchName: image.tmdb.org
        - matchName: thexem.info
        - matchPattern: "*.servarr.com"
        - matchPattern: "*.sonarr.tv"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
