---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pia-tun
  namespace: network
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      pia-tun:
        annotations:
          secret.reloader.stakater.com/reload: pia-tun-secret

        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          pia-tun:
            image:
              repository: olsonalexw/k8s-wireguard-pia
              tag: latest
            env:
              TZ: ${TIMEZONE}
              PORT_FORWARDING: "true"
              LOCAL_NETWORKS: "10.69.0.0/16"
              PORT_API_ENABLED: "true"
              PORT_API_URL: "qbittorrent.media.svc.cluster.local"
              METRICS: "true"
            envFrom:
              - secretRef:
                  name: pia-tun-secret
            securityContext:
              runAsUser: 0
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - NET_ADMIN  # For WireGuard/iptables
                drop:
                  - ALL
            resources:
              requests:
                cpu: 50m
                memory: 50M
              limits:
                cpu: 200m
                memory: 100M
                squat.ai/tun: 1  # TUN device limit

    service:
      main:  # Exposes proxies via ClusterIP (internal access only)
        controller: pia-tun
        ports:
          http:  # HTTP proxy
            port: 8888
            targetPort: 8888
          socks5:  # SOCKS5
            port: 1080
            targetPort: 1080
          metrics:
            port: 9090
            targetPort: 9090
          wireguard:  # wg0 for direct binds (if needed)
            port: 51820
            targetPort: 51820
            protocol: UDP

    persistence:
      config:
        enabled: true
        type: emptyDir  # Ephemeral for logs/state
        advancedMounts:
          pia-tun:
            pia-tun:
              - path: /
