# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: cert-manager,dashboard,database,external-secrets,kube-system,media,network,observability,security,storage
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:iFUhMokz3ROtXCQ=,iv:aAwSbWLQC06BhlU0lBhrg2KzpbDtGKh6r9gym1G66l8=,tag:waj9ohgZC40Fi5gleFE5Rg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:4GClUtBofjh9d5wQo7c3uPVr9FU=,iv:U/unUmnSKOMyrLUyMQ1MJRaxTQB0pJt06k8J8ij+9Pw=,tag:Rc+MP+RNiMLf0gL7VBmxvg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:prtKF41ZopHxwMB+3fXc0dMac894Im/e3FaWkDnXKEawKrv6,iv:g6j9fWzcnwFchMVc5avBm1YHrFgWhOU/OGVCsDrGs6Q=,tag:LpqtxdZgXI/fc6hiMziNeQ==,type:str]
    ZONE_ID: ENC[AES256_GCM,data:5NnM8vQNGoVeanYCh8LZdjsJSBIlPLLy8J8olhMZ+3k=,iv:/X+xMQd5WfmhFkjJ7xc9E/g/a2gSb4InMRE8OPKdg2M=,tag:3b0EbZdz3WcMFI7hf6KWiw==,type:str]
    GRAFANA_USER: ENC[AES256_GCM,data:h+QNvlE=,iv:Wa5ZzC/UDRMCkphpF5FEJd/SL97kgHAt2AreFdI6VNI=,tag:uiRLL9qYJ8ARRywelfkOfA==,type:str]
    GRAFANA_PASS: ENC[AES256_GCM,data:9d6OPbkWiTcTeQpr7llzHrM=,iv:7NIZeFYnYNqzafWJVNFCU+c7u/P0JY5D6KK4+uJmmXY=,tag:IfM4hAN7h1WNH6kgCcgfkw==,type:str]
sops:
    age:
        - recipient: age1h5suln4phcc5qzs2sfmkee39kzhdskmmwzzf5e46egaxqr64l9uskqeh4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVWZHQS9Jdndrd3RtR00w
            TENFK1FhZ05RR3lyUnczc3BnREd3WHlQYURZCnE3YVdJKzNGQkpqUTJlVE5zdFpF
            UStZSU5tVFUvRUVEZjlaN2V6eENmQ0UKLS0tIFcrck5ZbERNRGhBSitYQkcwYlRP
            K2c1Nzk1R2ZYZEF4R1lOa3dnRFNHRHcK6QOin/dgvqCbJSrshOCXnZtf6wgLeQpV
            rlzHTPrrD9nxmvZjcGAtR+uUgqKGUyX5WNphsLldGwDTqL7Ei7+UdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T05:38:15Z"
    mac: ENC[AES256_GCM,data:i5qUvb+qIZiXyQfzBi1X8oMoAzZyg/xuhgFvnH93ghqkeAGH+3/rLwPufPBMNEfVBX8fh3/TGYGm8HumGqyOS9rOaDWo4ZvwjBOcpsRbqZw7VeuPMe5kcz5C4cxNPs26mfqRE7vYPH8Ifmdg55Ga9mKDKEiZV0jmsIh+SJYM82w=,iv:a+6HUF49wgGno+3yhmK5rzgvXuGfi5MxM4AUUAwZR+0=,tag:TTv4ASVcq8+CfUTO0UBBAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
