# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:iFUhMokz3ROtXCQ=,iv:aAwSbWLQC06BhlU0lBhrg2KzpbDtGKh6r9gym1G66l8=,tag:waj9ohgZC40Fi5gleFE5Rg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:4GClUtBofjh9d5wQo7c3uPVr9FU=,iv:U/unUmnSKOMyrLUyMQ1MJRaxTQB0pJt06k8J8ij+9Pw=,tag:Rc+MP+RNiMLf0gL7VBmxvg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:prtKF41ZopHxwMB+3fXc0dMac894Im/e3FaWkDnXKEawKrv6,iv:g6j9fWzcnwFchMVc5avBm1YHrFgWhOU/OGVCsDrGs6Q=,tag:LpqtxdZgXI/fc6hiMziNeQ==,type:str]
    ZONE_ID: ENC[AES256_GCM,data:5NnM8vQNGoVeanYCh8LZdjsJSBIlPLLy8J8olhMZ+3k=,iv:/X+xMQd5WfmhFkjJ7xc9E/g/a2gSb4InMRE8OPKdg2M=,tag:3b0EbZdz3WcMFI7hf6KWiw==,type:str]
    GRAFANA_USER: ENC[AES256_GCM,data:h+QNvlE=,iv:Wa5ZzC/UDRMCkphpF5FEJd/SL97kgHAt2AreFdI6VNI=,tag:uiRLL9qYJ8ARRywelfkOfA==,type:str]
    GRAFANA_PASS: ENC[AES256_GCM,data:p7J02M1iOONoR1JOPBSypSw=,iv:MYV7VMopkZlk8wJDQCOV0cn46gAysUYTT3WDRf5BKL4=,tag:lZdmuH+AaClE2uhIWf7DSw==,type:str]
sops:
    age:
        - recipient: age1h5suln4phcc5qzs2sfmkee39kzhdskmmwzzf5e46egaxqr64l9uskqeh4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVWZHQS9Jdndrd3RtR00w
            TENFK1FhZ05RR3lyUnczc3BnREd3WHlQYURZCnE3YVdJKzNGQkpqUTJlVE5zdFpF
            UStZSU5tVFUvRUVEZjlaN2V6eENmQ0UKLS0tIFcrck5ZbERNRGhBSitYQkcwYlRP
            K2c1Nzk1R2ZYZEF4R1lOa3dnRFNHRHcK6QOin/dgvqCbJSrshOCXnZtf6wgLeQpV
            rlzHTPrrD9nxmvZjcGAtR+uUgqKGUyX5WNphsLldGwDTqL7Ei7+UdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T16:29:01Z"
    mac: ENC[AES256_GCM,data:wwmNr2aOm0h42qdNnyTignwEX3y9eIJU8sy/ykc1E4ye0NC5QnSiMLm1yHXlpnlmNFTp0DtcMYRovZHSFhSfumZNq1slXr0dcwKgbmt0HWuCWal7DX9awIMDsKR817x8qw8Fo06IyvAOu2xzYM6K3IC8XCfYR7XkrgBDWhG7JMA=,iv:hB6TW0P6SwGAnksOiX8d9uJcfVaOJJksQJsdlQKw4Jw=,tag:goe8wQK0VH5lsfXyUhGhLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
