---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: cert-manager/cert-manager
