---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-db
  namespace: media
spec:
  refreshInterval: 1m  # Sync every minute
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: radarr-db-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: postgres-pguser-radarr # Name of kubernetes secret in database namespace
        property: password
    - secretKey: host
      remoteRef:
        key: postgres-pguser-radarr
        property: host
    - secretKey: port
      remoteRef:
        key: postgres-pguser-radarr
        property: port
