apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: csi-driver-nfs
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: csi-driver-nfs
  egress:
    - toEntities:
        - kube-apiserver
