# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  releaseName: plex
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: nvidia-device-plugin
      namespace: kube-system
    - name: csi-driver-nfs
      namespace: storage
  values:
    controllers:
      main:
        type: deployment
        strategy: Recreate
        initContainers:
          cuda-symlink:
            image:
              repository: busybox
              tag: 1.36
              pullPolicy: IfNotPresent
            command:
              - /bin/sh
              - -c
            args:
              - |
                set -e
                mkdir -p /usr/lib/plexmediaserver/lib
                ln -sf /usr/local/glibc/usr/lib/libcuda.so.1 /usr/lib/plexmediaserver/lib/libcuda.so.1
                ln -sf /usr/local/glibc/usr/lib/libcuda.so   /usr/lib/plexmediaserver/lib/libcuda.so
                ln -sf /usr/local/glibc/usr/lib/libcuda.so.570.195.03 /usr/lib/plexmediaserver/lib/libcuda.so.570.195.03
                echo "Symlinks created in Plex lib dir:"
                ls -l /usr/lib/plexmediaserver/lib | grep cuda || echo "No symlinks visible?"
            volumeMounts:
              - mountPath: /plex-libs
                name: plex-libs
        containers:
          main:
            image:
              # repository: ghcr.io/home-operations/plex
              # repository: plexinc/pms-docker
              repository: linuxserver/plex
              tag: latest
            env:
              TZ: ${TIMEZONE}
              PUID: "1001"
              PGID: "1001"
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
              LD_LIBRARY_PATH: "/plex-libs/lib:/usr/lib/plexmediaserver/lib:/usr/local/glibc/usr/lib:/usr/lib:${LD_LIBRARY_PATH}"
            volumeMounts:
              - mountPath: /plex-libs
                name: plex-libs
            resources:
              requests:
                cpu: 49m
                memory: 2048M
                nvidia.com/gpu: 1
              limits:
                memory: 4046M
                nvidia.com/gpu: 1

    service:
      main:
        controller: main
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth-restrict-networks@kubernetescrd"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Plex
          gethomepage.dev/group: Media
          gethomepage.dev/icon: plex.png
          gethomepage.dev/description: Media Player
          gethomepage.dev/href: https://plex.${SECRET_DOMAIN}
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "${SECRET_DOMAIN/./-}-production-tls"

    persistence:
      plex-libs:
        enabled: true
        type: emptyDir
        medium: ""
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: nfs-csi
        accessMode: ReadWriteMany
        size: 2Gi
      media:
        enabled: true
        existingClaim: nfs-media-pvc
      transcode:
        enabled: true
        type: emptyDir

    defaultPodOptions:
      runtimeClassName: nvidia
      nodeSelector:
        nvidia.feature.node.kubernetes.io/gpu: "true"
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: false
        # runAsUser: 1001
        # runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
