apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: reflector
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: reflector
  egress:
    - toEntities:
        - kube-apiserver
